### ISSUE TITLE
Loss of connection after a few hours of use

### ISSUE THREAD

**Issue by canoben** [OpenEPaperLink/OpenEPaperLink#346] opened 2024-07-03 09:11 UTC
**Describe the bug**
I have a few tags and they work fine using a Home Assistant automation. But after a few hours of use, the connection to the AP is lost, the built-in screen turns black and the RGB LED displays a constant blue or green light (instead of pulsating). Disconnecting the power and rebooting the device restores functionality.

**To Reproduce**
1. Connect the OpenEPaperLink AP to wifi network
2. Use it for a few hours
3. Unit stops working

**Expected behaviour**
The device should work continuously without needing a reboot every day.

**Screenshots**
screen goes completely black

**Additional context**
I'm using latest firmware 2.60b

**Comment by Misiu** [comment] 2024-07-04 13:07
I have a similar issue.
I'm using BLE_ONLY firmware on ESP32S3 (installed via https://install.openepaperlink.de/), on the firmware updates page I see these variables:
```
env:                BLE_ONLY_AP
build date:         2024-05-07 18:05
esp32 version:      ble_test3
filesystem version: unknown <- not matching!
psram size:         8378503
flash size:         16777216
--------------------------
```

I have a single BLE GICIsky 2.9 display and I'm controlling if from Home Assistant.
After some time I noticed errors in Home Assistant logs and was unable to access Access Point via IP, restarting the ESP solved the issue.
This situation happened 3 times till now.

Not sure how to debug this or get any logs that could help with fixing the issue.

**Comment by r2kch** [comment] 2024-07-06 15:17
had the same issue with my MiniAP V4 - downgraded to 2.52. Please be aware that there is no or limited ble support. 
Can you grab the logs via the UART port? (see: https://docs.espressif.com/projects/esp-idf/en/stable/esp32/get-started/establish-serial-connection.html)

**Comment by Derek-K** [comment] 2024-09-01 15:52
> For reference, I saw this update was supposed rolled into 2.07 **fix: in rare cases, an AP didn't connect to a WiFi network due to some tight timing** [1d03eed](https://github.com/OpenEPaperLink/OpenEPaperLink/commit/1d03eedfd65354ccd801277451e95338da093976)

However, I looked at the code change, it doesn't really explain why there is a WiFi disconnection in the first place. 

https://github.com/OpenEPaperLink/OpenEPaperLink/blob/1d03eedfd65354ccd801277451e95338da093976/ESP32_AP-Flasher/src/wifimanager.cpp#L140-L145

https://github.com/OpenEPaperLink/OpenEPaperLink/blob/1d03eedfd65354ccd801277451e95338da093976/ESP32_AP-Flasher/src/wifimanager.cpp#L211-L214

It just adds `delay(100)` in `wifimanager`

**Comment by foorschtbar** [comment] 2024-09-04 14:56
Same problem here with 2.60b. Lost wifi connection nearly every day with my ESP32S3 mini AP

**Comment by nlimper** [comment] 2024-09-04 15:08
It can be caused by all kinds of reasons. The people who react 'me too!' could have a very different cause as the original poster. Without extensive debugging, it's impossible to fix. It can be caused by all kinds of things, including your Wifi AP settings, including using an instable power supply for the OEPL AP.

When BLE is enabled: it's experimental, and the BLE stack is kind of buggy. Won't fix.

The reference to [1d03eed](https://github.com/OpenEPaperLink/OpenEPaperLink/commit/1d03eedfd65354ccd801277451e95338da093976): that's completely unrelated

To debug, capture the serial output of the AP, to see if there's anything interesting happening. Also, check whether it also hangs if you don't make a HA connection. Also, change the power supply of your AP to a different one to rule that out too, it has happened more often that that was the problem.

**Closed by nlimper** 2024-09-04 15:08 UTC
Labels: bug

**Comment by foorschtbar** [comment] 2024-09-04 15:36
You can also see it differently. I notice a problem and first check if there is already a similar one and then someone describes a similar problem. What should I do? Open a new issue? I think it would be helpful to tell the OP in which constellation (hardware + firmware) I also have the wifi issue, so that WE can look for similarities to solve the error.

**Comment by nlimper** [comment] 2024-09-04 15:40
Fair enough. As long as all participants realise that 'the wifi issue' can be different (and will have different causes) for everybody :-)

**Comment by njordan77** [comment] 2026-05-23 20:19
my 2.85 crashed also (wifi lost) every few days. its a ESP32-S3 with the C6 combination (YellowAP). is there anybody else having this issue. repowering the ESPs makes it all work again for 2-4 days.
