### ISSUE TITLE
Solum 5.85

### ISSUE THREAD

**Issue by vaughnlfisher** [OpenEPaperLink/OpenEPaperLink#355] opened 2024-08-11 13:56 UTC
Hi again

After a lot of messing around, I uploaded the following bin from another post, m3 4.2 Firmware. https://github.com/jjwbruijn/OpenEPaperLink/files/14625655/varuicrdump-4.2-ssd-experimental.zip
It has worked on a portion of the screen, and its upsdie down. But very positive.
Could you explain why this worked an none of the other FW bins I uploaded. Attached my dump
working_infopage.zip

See issue #304

![image](https://github.com/user-attachments/assets/b190eb9e-1987-46f6-9124-ef0cdcbe3005)

**Comment by nlimper** [comment] 2024-09-04 07:59
The 5.85" is not supported yet, but the fact that most of it works is very promising :-)
I will close this one, as it is a duplicate of https://github.com/OpenEPaperLink/OpenEPaperLink/issues/304

**Closed by nlimper** 2024-09-04 07:59 UTC

**Comment by MaxwellJK** [comment] 2025-10-02 11:31
hi @vaughnlfisher I have the same tag. May I ask you what procedure you followed to flash it?
Thanks

**Comment by kirelam** [comment] 2026-06-05 12:59
> hi [@vaughnlfisher](https://github.com/vaughnlfisher) I have the same tag. May I ask you what procedure you followed to flash it? Thanks

Same question!
